- name: Deploy website on EC2 server
  hosts: all
  become: true
  tasks:

    - name: update apt packages
      apt:  
        update_cache: yes

    - name: Install web apache server
      apt: 
        name: apache2
        state: present
    
    - name: start and enable web server 
      service: 
        name: apache2
        state: started
        enabled: yes

    - name: Install git
      apt:
        name: git
        state: present

    - name: set correct permission for ssh key file
      file: 
        path: "{{ playbook_dir }}/../infra-as-code/MyEC2InstanceLoginKey"
        mode: '0600'

    - name: copy website files to apache web server file
      copy: 
        src: "{{ playbook_dir }}/../static-website/"
        dest: /var/www/html/

    - name: set the premission for apache
      file: 
        path: /var/www/html
        owner: www-data
        group: www-data
        mode: '0755'  ## here '0' meaning that there is no special permission is set
        recurse: yes
        state: directory
