- name: Deploy website on EC2 server
  hosts: all
  become: true
  tasks:

    - name: update apt packages
      apt:  
        update_cache: yes

    - name: Install web apache server
      apt: 
        name: apache2
        state: present
    
    - name: start and enable web server 
      service: 
        name: apache2
        state: started
        enabled: yes

    - name: Install git
      apt:
        name: git
        state: present

    - name: clone the website file
      git: 
        repo: https://github.com/Ayushi-gupta2001/Terraform-Ansible-Jenkins.git
        dest: /tmp/website
        version: test

    - name: Copy the file to wesbite folder
      copy:
        src: /tmp/website/static-website/
        dest: /var/www/html
      remote_src: yes
      
    - name: set the premission for apache
      file: 
        path: /var/www/html
        owner: www-data
        group: www-data
        mode: '0755'  ## here '0' meaning that there is no special permission is set
        recurse: yes
        state: directory
